### ISSUE TITLE
Master internal IP management

### ISSUE THREAD

**Issue by danisla** [GoogleCloudPlatform/terraform-google-k8s-gce#7]
<a href="https://github.com/danisla"><img src="https://avatars0.githubusercontent.com/u/323725?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [danisla](https://github.com/danisla)**
_Monday Aug 21, 2017 at 21:15 GMT_
_Originally opened as https://github.com/danisla/terraform-google-k8s-gce/issues/7_

----

The master IP has to be manually assigned per region and ideally would be outside any auto-assignable range. 
Should this be the responsibility of the user or do we provide some sensible default per-region in a map variable (see nat-gateway module for example map). Could also be done with a VIP, and route rule.

**Comment by g-awmalik** [comment]
Apologies for being so overdue on this.

I think it's better to leave this as user's responsibility and keep module free of that logic.

**Comment by g-awmalik** [comment]
Closing since this is stale now. Please reopen if necessary.
